# for details on settings, see https://docs.rendercv.com/user_guide/yaml_input_structure/settings/
rendercv_settings:
  render_command:
    design: assets/rendercv/design.yaml
    locale: assets/rendercv/locale.yaml
    typst_path: assets/rendercv/rendercv_output/kamil_mikolaj_cv.typ
    pdf_path: assets/rendercv/rendercv_output/kamil_mikolaj_cv.pdf
    markdown_path: assets/rendercv/rendercv_output/kamil_mikolaj_cv.md
    html_path: assets/rendercv/rendercv_output/kamil_mikolaj_cv.html
    png_path: assets/rendercv/rendercv_output/kamil_mikolaj_cv.png
    dont_generate_markdown: true
    dont_generate_html: true
    dont_generate_pdf: false
    dont_generate_png: true
  bold_keywords: []
